//! Audit events for session lifecycle tracking.

/// Severity level of an audit event.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuditLevel {
    /// Informational event.
    Info,
    /// Warning event.
    Warn,
    /// Error-level event.
    Error,
    /// Debug-level detail.
    Debug,
}

/// An audit event generated by the session subsystem.
#[derive(Debug, Clone)]
pub enum SessionAuditEvent {
    /// A new session was created.
    SessionCreated { session_id: String, user: String },
    /// A state transition occurred.
    StateTransition { from: String, to: String },
    /// The heartbeat monitor detected a timeout.
    HeartbeatTimeout { missed: u32 },
    /// A worker was started.
    WorkerStarted { worker: String },
    /// A worker was stopped.
    WorkerStopped { worker: String },
    /// A worker failed.
    WorkerFailed { worker: String, reason: String },
    /// A restart attempt was made.
    RestartAttempt { count: u32, backoff_ms: u64 },
    /// The session entered safe mode.
    SafeModeEntered,
    /// A plugin was quarantined.
    PluginQuarantined { plugin_id: String },
    /// A sandbox violation was detected.
    SandboxViolation { detail: String },
    /// A resource limit warning was raised.
    ResourceLimitWarning {
        resource: String,
        usage_percent: f64,
    },
    /// A session was resumed from a disconnected state.
    SessionResumed {
        session_id: String,
        token_id: String,
    },
    /// The session was terminated.
    SessionTerminated { reason: String },
}

impl SessionAuditEvent {
    /// The severity level of this event.
    #[must_use]
    pub fn level(&self) -> AuditLevel {
        match self {
            Self::SessionCreated { .. }
            | Self::StateTransition { .. }
            | Self::WorkerStarted { .. }
            | Self::WorkerStopped { .. }
            | Self::SessionResumed { .. } => AuditLevel::Info,

            Self::HeartbeatTimeout { .. }
            | Self::ResourceLimitWarning { .. }
            | Self::RestartAttempt { .. } => AuditLevel::Warn,

            Self::WorkerFailed { .. }
            | Self::SafeModeEntered
            | Self::PluginQuarantined { .. }
            | Self::SandboxViolation { .. }
            | Self::SessionTerminated { .. } => AuditLevel::Error,
        }
    }

    /// A short name identifying this event type.
    #[must_use]
    pub fn event_name(&self) -> &str {
        match self {
            Self::SessionCreated { .. } => "session_created",
            Self::StateTransition { .. } => "state_transition",
            Self::HeartbeatTimeout { .. } => "heartbeat_timeout",
            Self::WorkerStarted { .. } => "worker_started",
            Self::WorkerStopped { .. } => "worker_stopped",
            Self::WorkerFailed { .. } => "worker_failed",
            Self::RestartAttempt { .. } => "restart_attempt",
            Self::SafeModeEntered => "safe_mode_entered",
            Self::PluginQuarantined { .. } => "plugin_quarantined",
            Self::SandboxViolation { .. } => "sandbox_violation",
            Self::ResourceLimitWarning { .. } => "resource_limit_warning",
            Self::SessionResumed { .. } => "session_resumed",
            Self::SessionTerminated { .. } => "session_terminated",
        }
    }
}
