//! Audit events for GPU renderer lifecycle tracking.
//!
//! Mirrors the audit pattern from `liquide-session` for consistent
//! observability across the system.

/// Severity level of a GPU audit event.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuditLevel {
    /// Informational event.
    Info,
    /// Warning event.
    Warn,
    /// Error-level event.
    Error,
    /// Debug-level detail.
    Debug,
}

/// An audit event generated by the GPU renderer subsystem.
#[derive(Debug, Clone)]
pub enum GpuAuditEvent {
    /// A GPU device was successfully initialised.
    DeviceInitialized {
        /// Vendor name.
        vendor: String,
        /// Selected profile name.
        profile: String,
    },
    /// The Vulkan device was lost.
    DeviceLost {
        /// Reason for the loss.
        reason: String,
    },
    /// The renderer fell back to CPU rendering.
    FallbackActivated {
        /// Why fallback was triggered.
        reason: String,
    },
    /// The renderer returned from CPU fallback to GPU rendering.
    FallbackDeactivated,
    /// VRAM usage exceeded a warning threshold.
    VramWarning {
        /// Current usage as a percentage of the session budget.
        used_pct: f64,
    },
    /// A frame was rendered successfully.
    FrameRendered {
        /// Total render time in microseconds.
        time_us: u64,
    },
    /// A pipeline stage encountered an error.
    PipelineError {
        /// Which pipeline stage failed.
        stage: String,
        /// Description of the error.
        error: String,
    },
}

impl GpuAuditEvent {
    /// The severity level of this event.
    #[must_use]
    pub fn level(&self) -> AuditLevel {
        match self {
            Self::DeviceInitialized { .. }
            | Self::FallbackDeactivated
            | Self::FrameRendered { .. } => AuditLevel::Info,

            Self::VramWarning { .. }
            | Self::FallbackActivated { .. } => AuditLevel::Warn,

            Self::DeviceLost { .. }
            | Self::PipelineError { .. } => AuditLevel::Error,
        }
    }

    /// A short name identifying this event type.
    #[must_use]
    pub fn event_name(&self) -> &str {
        match self {
            Self::DeviceInitialized { .. } => "device_initialized",
            Self::DeviceLost { .. } => "device_lost",
            Self::FallbackActivated { .. } => "fallback_activated",
            Self::FallbackDeactivated => "fallback_deactivated",
            Self::VramWarning { .. } => "vram_warning",
            Self::FrameRendered { .. } => "frame_rendered",
            Self::PipelineError { .. } => "pipeline_error",
        }
    }
}
