[package]
name = "fuzz_cbor_decoder"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
liquide-protocol = { path = "../../../crates/liquide-protocol" }

[[bin]]
name = "fuzz_cbor_decoder"
path = "fuzz_target.rs"
doc = false
