[package]
name = "fuzz_frame_parser"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
bytes = "1"
libfuzzer-sys = "0.4"
liquide-protocol = { path = "../../../crates/liquide-protocol" }

[[bin]]
name = "fuzz_frame_parser"
path = "fuzz_target.rs"
doc = false
