[package]
name = "liquide-encoder"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
liquide-common.workspace = true
liquide-compositor.workspace = true
liquide-protocol.workspace = true
thiserror.workspace = true
tracing.workspace = true
zstd.workspace = true
lz4_flex.workspace = true
bytes.workspace = true
serde.workspace = true
