[package]
name = "fuzz_video_decoder"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
liquide-client-renderer = { path = "../../../crates/liquide-client-renderer" }
liquide-encoder-hw = { path = "../../../crates/liquide-encoder-hw" }

[[bin]]
name = "fuzz_video_decoder"
path = "fuzz_target.rs"
doc = false
