[package]
name = "liquide-shell"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
liquide-compositor.workspace = true
liquide-context-menu.workspace = true
liquide-dock.workspace = true
liquide-input.workspace = true
liquide-interop.workspace = true
liquide-platform.workspace = true
liquide-ui.workspace = true
liquide-theme-css = { path = "../liquide-theme-css" }
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
criterion.workspace = true
serde_json = "1"

[[bench]]
name = "shell_bench"
harness = false
