//! Audit trail for assistance sessions.

/// Severity level of an audit event.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuditLevel {
    /// Informational.
    Info,
    /// Warning.
    Warn,
    /// Debug-level detail.
    Debug,
}

/// An audit event generated by the assistance framework.
#[derive(Debug, Clone)]
pub enum AssistanceAuditEvent {
    /// An assistance request was made.
    Requested {
        observer_id: String,
        target_session_id: String,
        mode: String,
    },
    /// The owner granted consent.
    ConsentGranted {
        observer_id: String,
        target_session_id: String,
    },
    /// The owner denied consent.
    ConsentDenied {
        observer_id: String,
        target_session_id: String,
    },
    /// The consent prompt timed out.
    ConsentTimeout {
        observer_id: String,
        target_session_id: String,
    },
    /// An assistance session started.
    Started {
        session_id: String,
        observer_id: String,
        mode: String,
    },
    /// The session was escalated to a new mode.
    Escalated {
        session_id: String,
        new_mode: String,
    },
    /// The owner reclaimed control.
    OwnerReclaimed { session_id: String },
    /// The session ended.
    Ended {
        session_id: String,
        reason: String,
    },
    /// A stealth session started.
    StealthStarted {
        observer_id: String,
        target_session_id: String,
    },
    /// A stealth session is active (periodic audit).
    StealthActive {
        observer_id: String,
        target_session_id: String,
        duration_seconds: u64,
    },
    /// A stealth session ended.
    StealthEnded {
        observer_id: String,
        target_session_id: String,
        duration_seconds: u64,
    },
    /// A chat message was sent.
    ChatMessageSent {
        session_id: String,
        sender: String,
    },
    /// An invite was created.
    InviteCreated {
        code: String,
        created_by: String,
    },
    /// An invite was used.
    InviteUsed {
        code: String,
        used_by: String,
    },
}

impl AssistanceAuditEvent {
    /// The severity level of this event.
    #[must_use]
    pub fn level(&self) -> AuditLevel {
        match self {
            Self::Requested { .. }
            | Self::ConsentGranted { .. }
            | Self::Started { .. }
            | Self::Ended { .. }
            | Self::InviteCreated { .. }
            | Self::InviteUsed { .. }
            | Self::ChatMessageSent { .. } => AuditLevel::Info,

            Self::ConsentDenied { .. }
            | Self::ConsentTimeout { .. }
            | Self::StealthStarted { .. }
            | Self::StealthEnded { .. }
            | Self::OwnerReclaimed { .. }
            | Self::Escalated { .. } => AuditLevel::Warn,

            Self::StealthActive { .. } => AuditLevel::Debug,
        }
    }

    /// A short name identifying this event type.
    #[must_use]
    pub fn event_name(&self) -> &str {
        match self {
            Self::Requested { .. } => "requested",
            Self::ConsentGranted { .. } => "consent_granted",
            Self::ConsentDenied { .. } => "consent_denied",
            Self::ConsentTimeout { .. } => "consent_timeout",
            Self::Started { .. } => "started",
            Self::Escalated { .. } => "escalated",
            Self::OwnerReclaimed { .. } => "owner_reclaimed",
            Self::Ended { .. } => "ended",
            Self::StealthStarted { .. } => "stealth_started",
            Self::StealthActive { .. } => "stealth_active",
            Self::StealthEnded { .. } => "stealth_ended",
            Self::ChatMessageSent { .. } => "chat_message_sent",
            Self::InviteCreated { .. } => "invite_created",
            Self::InviteUsed { .. } => "invite_used",
        }
    }
}
