//! Recognizable 8×16 bitmap shapes for the handful of Unicode "dingbat"
//! codepoints the devtools UI emits as text (toolbar icons + tree-expand
//! arrows + Scene-tab style-editor markers).
//!
//! These codepoints (⊕ ◫ ⊥ ⊢ ▶ ▼ ✓ ○) are absent from the bundled UI fonts
//! (Inter / Roboto both map them to glyph 0 — verified), so when shaped they
//! resolve to `.notdef` and the renderer drops to the 8×16 bitmap fallback.
//! Without a real pattern here that fallback paints `FALLBACK_GLYPH` — a solid
//! filled rectangle — so every devtools icon shows up as an opaque block
//! (t167 bug 3).
//!
//! Rather than ship a heavy symbol font or wire a brand-new icon scene node
//! through the CSS pipeline, we give each of these specific codepoints a small
//! recognizable glyph here. They flow through the SAME supersample + box-filter
//! AA path as every other bitmap glyph (`rasterize_glyph_bitmap`), so they come
//! out smooth and correctly advanced — and crucially they are NOT uniform solid
//! blocks: each has internal structure (an outline, a triangle, a tack).
//!
//! Each glyph is 8 px wide × 16 px tall, one byte per row, MSB = leftmost pixel
//! (identical encoding to `FONT_DATA`).

/// Return a recognizable 8×16 bitmap for a devtools icon codepoint, or `None`
/// if `ch` is not one of the known devtools dingbats.
#[must_use]
pub(super) fn icon_glyph(ch: char) -> Option<&'static [u8; 16]> {
    match ch {
        '\u{25B6}' => Some(&TRIANGLE_RIGHT), // ▶ tree collapsed
        '\u{25BC}' => Some(&TRIANGLE_DOWN),  // ▼ tree expanded
        '\u{2295}' => Some(&CIRCLED_PLUS),   // ⊕ element picker
        '\u{25EB}' => Some(&SPLIT_WINDOW),   // ◫ detach
        '\u{22A5}' => Some(&DOCK_BOTTOM),    // ⊥ dock bottom
        '\u{22A2}' => Some(&DOCK_RIGHT),     // ⊢ dock right
        '\u{2713}' => Some(&CHECK_MARK),     // ✓ applied edit
        '\u{25CB}' => Some(&RING),           // ○ pending edit
        _ => None,
    }
}

/// ▶ — right-pointing filled triangle (collapsed tree row).
#[rustfmt::skip]
static TRIANGLE_RIGHT: [u8; 16] = [
    0x00, // ........
    0x00, // ........
    0x40, // .#......
    0x60, // .##.....
    0x70, // .###....
    0x78, // .####...
    0x7C, // .#####..
    0x7E, // .######.
    0x7E, // .######.
    0x7C, // .#####..
    0x78, // .####...
    0x70, // .###....
    0x60, // .##.....
    0x40, // .#......
    0x00, // ........
    0x00, // ........
];

/// ▼ — down-pointing filled triangle (expanded tree row).
#[rustfmt::skip]
static TRIANGLE_DOWN: [u8; 16] = [
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0xFE, // #######.
    0xFE, // #######.
    0x7C, // .#####..
    0x7C, // .#####..
    0x38, // ..###...
    0x38, // ..###...
    0x10, // ...#....
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
];

/// ⊕ — circle with a plus inside (element picker).
#[rustfmt::skip]
static CIRCLED_PLUS: [u8; 16] = [
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x3C, // ..####..
    0x5A, // .#.##.#.
    0x99, // #..##..#
    0xBD, // #.####.#
    0xBD, // #.####.#
    0x99, // #..##..#
    0x5A, // .#.##.#.
    0x3C, // ..####..
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
];

/// ◫ — square with a vertical divider (detach into its own window).
#[rustfmt::skip]
static SPLIT_WINDOW: [u8; 16] = [
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0xFF, // ########
    0x99, // #..##..#
    0x99, // #..##..#
    0x99, // #..##..#
    0x99, // #..##..#
    0x99, // #..##..#
    0x99, // #..##..#
    0xFF, // ########
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
];

/// ⊥ — vertical stem on a horizontal base (dock to bottom).
#[rustfmt::skip]
static DOCK_BOTTOM: [u8; 16] = [
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x18, // ...##...
    0x18, // ...##...
    0x18, // ...##...
    0x18, // ...##...
    0x18, // ...##...
    0x18, // ...##...
    0x18, // ...##...
    0xFF, // ########
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
];

/// ⊢ — vertical bar with a horizontal stem to the right (dock to right).
#[rustfmt::skip]
static DOCK_RIGHT: [u8; 16] = [
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0xC0, // ##......
    0xC0, // ##......
    0xC0, // ##......
    0xFE, // #######.
    0xFE, // #######.
    0xC0, // ##......
    0xC0, // ##......
    0xC0, // ##......
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
];

/// ✓ — check mark (an applied style edit).
#[rustfmt::skip]
static CHECK_MARK: [u8; 16] = [
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x03, // ......##
    0x06, // .....##.
    0x0C, // ....##..
    0x18, // ...##...
    0xD8, // ##.##...
    0xF0, // ####....
    0x70, // .###....
    0x20, // ..#.....
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
];

/// ○ — hollow ring (a pending style edit).
#[rustfmt::skip]
static RING: [u8; 16] = [
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x3C, // ..####..
    0x42, // .#....#.
    0x81, // #......#
    0x81, // #......#
    0x81, // #......#
    0x81, // #......#
    0x42, // .#....#.
    0x3C, // ..####..
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
    0x00, // ........
];
