[package]
name = "liquide-platform"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
liquide-compositor.workspace = true
liquide-input.workspace = true
liquide-interop.workspace = true
serde.workspace = true
thiserror.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
liquide-drm.workspace = true
libc = "0.2"

[dev-dependencies]
serde_json.workspace = true
