[package]
name = "liquide-render-thread"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
liquide-compositor = { workspace = true }
liquide-renderer-cpu = { workspace = true }
liquide-font-rasterizer = { workspace = true }
