//! Audit event types for the gateway.

/// Severity level of an audit event.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuditLevel {
    /// Normal operational event.
    Info,
    /// Something potentially concerning.
    Warn,
    /// A definite problem.
    Error,
    /// Verbose debug detail.
    Debug,
}

/// Audit events generated by the gateway.
#[derive(Debug, Clone)]
pub enum GatewayAuditEvent {
    /// A new client connection was accepted.
    ClientConnected {
        addr: String,
        transport: String,
    },
    /// A client disconnected.
    ClientDisconnected {
        addr: String,
        reason: String,
    },
    /// An authentication attempt was made.
    AuthAttempt {
        addr: String,
        method: String,
        success: bool,
    },
    /// An IP was banned due to repeated auth failures.
    AuthBanned {
        addr: String,
        reason: String,
    },
    /// A backend server registered with the gateway.
    ServerRegistered {
        server_id: String,
        addr: String,
    },
    /// A backend server was removed.
    ServerDeregistered {
        server_id: String,
        reason: String,
    },
    /// A server's health status changed.
    ServerHealthChanged {
        server_id: String,
        health: String,
    },
    /// A routing decision was made.
    RouteDecision {
        client: String,
        server: String,
        strategy: String,
        mode: String,
    },
    /// A relay session was started.
    RelayStarted {
        relay_id: String,
        client: String,
        server: String,
    },
    /// A relay session ended.
    RelayEnded {
        relay_id: String,
        bytes_total: u64,
        duration_sec: u64,
    },
    /// A rate limit was triggered for an IP.
    RateLimitTriggered {
        addr: String,
        rate: u32,
    },
    /// Configuration was reloaded.
    ConfigReloaded,
    /// A tarpit was engaged for an abusive IP.
    TarpitEngaged {
        addr: String,
        mode: String,
    },
}

impl GatewayAuditEvent {
    /// The severity level of this event.
    #[must_use]
    pub fn level(&self) -> AuditLevel {
        match self {
            Self::ClientConnected { .. }
            | Self::ClientDisconnected { .. }
            | Self::ServerRegistered { .. }
            | Self::RouteDecision { .. }
            | Self::RelayStarted { .. }
            | Self::RelayEnded { .. }
            | Self::ConfigReloaded => AuditLevel::Info,

            Self::AuthAttempt { success, .. } => {
                if *success {
                    AuditLevel::Info
                } else {
                    AuditLevel::Warn
                }
            }

            Self::ServerDeregistered { .. }
            | Self::ServerHealthChanged { .. }
            | Self::RateLimitTriggered { .. } => AuditLevel::Warn,

            Self::AuthBanned { .. }
            | Self::TarpitEngaged { .. } => AuditLevel::Error,
        }
    }

    /// A short name identifying this event type.
    #[must_use]
    pub fn event_name(&self) -> &str {
        match self {
            Self::ClientConnected { .. } => "client_connected",
            Self::ClientDisconnected { .. } => "client_disconnected",
            Self::AuthAttempt { .. } => "auth_attempt",
            Self::AuthBanned { .. } => "auth_banned",
            Self::ServerRegistered { .. } => "server_registered",
            Self::ServerDeregistered { .. } => "server_deregistered",
            Self::ServerHealthChanged { .. } => "server_health_changed",
            Self::RouteDecision { .. } => "route_decision",
            Self::RelayStarted { .. } => "relay_started",
            Self::RelayEnded { .. } => "relay_ended",
            Self::RateLimitTriggered { .. } => "rate_limit_triggered",
            Self::ConfigReloaded => "config_reloaded",
            Self::TarpitEngaged { .. } => "tarpit_engaged",
        }
    }
}
