//! Audit events for supervisor lifecycle tracking.

use crate::crash::CrashCategory;
use crate::downgrade::DowngradeLevel;

/// Severity level of an audit event.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AuditLevel {
    /// Informational event.
    Info,
    /// Warning event.
    Warn,
    /// Error-level event.
    Error,
    /// Debug-level detail.
    Debug,
}

/// An audit event generated by the supervisor.
#[derive(Debug, Clone)]
pub enum SupervisorAuditEvent {
    /// The supervisor daemon has started.
    SupervisorStarted,
    /// The supervisor daemon is stopping.
    SupervisorStopped,
    /// A session was spawned.
    SessionSpawned {
        /// Session identifier.
        session_id: String,
        /// User who owns the session.
        user: String,
    },
    /// A session was terminated.
    SessionTerminated {
        /// Session identifier.
        session_id: String,
        /// Reason for termination.
        reason: String,
    },
    /// A session crashed.
    SessionCrashed {
        /// Session identifier.
        session_id: String,
        /// Crash category.
        category: CrashCategory,
    },
    /// A restart was attempted for a session.
    RestartAttempted {
        /// Session identifier.
        session_id: String,
        /// Restart attempt number.
        attempt: u32,
    },
    /// A session admission was rejected.
    AdmissionRejected {
        /// User who was rejected.
        user: String,
        /// Reason for rejection.
        reason: String,
    },
    /// A downgrade action was applied.
    DowngradeApplied {
        /// Downgrade level applied.
        level: DowngradeLevel,
        /// Sessions affected.
        sessions: Vec<String>,
    },
    /// Policy was updated.
    PolicyUpdated,
    /// A resource warning was raised.
    ResourceWarning {
        /// Session identifier.
        session_id: String,
        /// Description of the warning.
        warning: String,
    },
    /// A control command was received on the IPC channel.
    ControlCommandReceived {
        /// String representation of the command.
        command: String,
    },
    /// An authentication attempt failed.
    AuthenticationFailed {
        /// User who failed authentication.
        user: String,
        /// Reason for failure.
        reason: String,
    },
}

impl SupervisorAuditEvent {
    /// The severity level of this event.
    #[must_use]
    pub fn level(&self) -> AuditLevel {
        match self {
            Self::SupervisorStarted
            | Self::SupervisorStopped
            | Self::SessionSpawned { .. }
            | Self::PolicyUpdated
            | Self::ControlCommandReceived { .. } => AuditLevel::Info,

            Self::RestartAttempted { .. }
            | Self::AdmissionRejected { .. }
            | Self::DowngradeApplied { .. }
            | Self::ResourceWarning { .. } => AuditLevel::Warn,

            Self::SessionTerminated { .. }
            | Self::SessionCrashed { .. }
            | Self::AuthenticationFailed { .. } => AuditLevel::Error,
        }
    }

    /// A short name identifying this event type.
    #[must_use]
    pub fn event_name(&self) -> &str {
        match self {
            Self::SupervisorStarted => "supervisor_started",
            Self::SupervisorStopped => "supervisor_stopped",
            Self::SessionSpawned { .. } => "session_spawned",
            Self::SessionTerminated { .. } => "session_terminated",
            Self::SessionCrashed { .. } => "session_crashed",
            Self::RestartAttempted { .. } => "restart_attempted",
            Self::AdmissionRejected { .. } => "admission_rejected",
            Self::DowngradeApplied { .. } => "downgrade_applied",
            Self::PolicyUpdated => "policy_updated",
            Self::ResourceWarning { .. } => "resource_warning",
            Self::ControlCommandReceived { .. } => "control_command_received",
            Self::AuthenticationFailed { .. } => "authentication_failed",
        }
    }
}
